#!/usr/bin/env bash
set -euo pipefail

out="${1:-dist}"
if [[ "$out" != "dist" ]]; then
  echo "refusing output outside the dedicated dist directory: $out" >&2
  exit 2
fi

required_go_version="go1.27.0"
actual_go_version="$(go env GOVERSION)"
if [[ "$actual_go_version" != "$required_go_version" ]]; then
  echo "Go $required_go_version is required; found $actual_go_version" >&2
  exit 1
fi

rm -rf -- "$out"
mkdir -p "$out"

# Copy the complete static tree, including nested assets and dotfiles.
cp -R web/. "$out/"
cp LICENSE THIRD_PARTY_NOTICES.md "$out/"

group_rooms_enabled="${TAILCAT_GROUP_ROOMS_ENABLED:-0}"
mobile_group_hosting_enabled="${TAILCAT_MOBILE_GROUP_HOSTING_ENABLED:-0}"
preview_invites_enabled="${TAILCAT_PREVIEW_INVITES:-0}"
native_files_enabled="${TAILCAT_NATIVE_FILES_ENABLED:-0}"
for release_switch in "$group_rooms_enabled" "$mobile_group_hosting_enabled" "$preview_invites_enabled" "$native_files_enabled"; do
  if [[ "$release_switch" != "0" && "$release_switch" != "1" ]]; then
    echo "Tailcat release switches must be 0 or 1" >&2
    exit 2
  fi
done
if [[ "$mobile_group_hosting_enabled" == "1" && "$group_rooms_enabled" != "1" ]]; then
  echo "mobile group hosting requires group rooms to be enabled" >&2
  exit 2
fi
group_rooms_js=false
mobile_group_hosting_js=false
preview_invites_js=false
native_files_js=false
source_sha="$(git rev-parse HEAD)"
if [[ ! "$source_sha" =~ ^[0-9a-f]{40}$ ]]; then
  echo "a verifiable Git source SHA is required" >&2
  exit 2
fi
if [[ "$native_files_enabled" == "1" ]]; then native_files_js=true; fi
if [[ "$group_rooms_enabled" == "1" ]]; then group_rooms_js=true; fi
if [[ "$mobile_group_hosting_enabled" == "1" ]]; then mobile_group_hosting_js=true; fi
if [[ "$preview_invites_enabled" == "1" ]]; then preview_invites_js=true; fi
printf '%s\n' \
  "// Generated by build.sh; do not add secrets to this public file." \
  "globalThis.__TAILCAT_GROUP_BETA__ ??= $group_rooms_js;" \
  "globalThis.__TAILCAT_MOBILE_GROUP_HOSTING__ ??= $mobile_group_hosting_js;" \
  "globalThis.__TAILCAT_PREVIEW_INVITES__ ??= $preview_invites_js;" \
  "globalThis.__TAILCAT_NATIVE_FILES__ ??= $native_files_js;" \
  "globalThis.__TAILCAT_SOURCE_SHA__ = '$source_sha';" \
  > "$out/runtime-config.js"

GOOS=js GOARCH=wasm go build -trimpath -ldflags="-s -w" -o "$out/main.wasm" .
gzip -9 -n -c "$out/main.wasm" > "$out/main.wasm.gz"

# wasm_exec.js must come from the exact Go toolchain that compiled main.wasm.
wasm_exec="$(go env GOROOT)/lib/wasm/wasm_exec.js"
if [[ ! -f "$wasm_exec" ]]; then
  echo "wasm_exec.js not found in the active Go toolchain: $wasm_exec" >&2
  exit 1
fi
cp "$wasm_exec" "$out/wasm_exec.js"
touch "$out/.nojekyll"

# Cloudflare Pages rejects files larger than 25 MiB. app.js fetches the gzip
# file directly and decompresses it in the browser, so production artifacts do
# not include the larger raw binary.
if [[ "${PAGES_BUILD:-}" == "1" ]]; then
  rm -- "$out/main.wasm"
fi

node scripts/build-manifest.mjs "$out"
echo "tailcat.app distribution written to $out/"
